### ISSUE TITLE
Crowdin

### ISSUE THREAD

**Issue by RoinujNosde** [Tomut0/SimpleClansStats#8]
Setup a Crowdin project integrated with the repository.

**Comment by RoinujNosde** [comment]
@comradekingu who are you? 🤔

**Comment by RoinujNosde** [comment]
Also add Crowdin badge to readme

**Comment by comradekingu** [comment]
@RoinujNosde Someone who has used Crowdin extensively.
It isn't a good tool, the terms and conditions aren't good, and it further is available as a disservice only.
Every now and then I let libre software project know of Weblate, and help out, which is how I end up not having to deal with Crowdin or Transifex.
